### ISSUE TITLE
Logs in production

### ISSUE THREAD

**Issue by NAlexandrov** [vadimpronin/guacamole-lite#15]
Can you disable log when NODE_ENV=production? Or console.log can be replaced to [debug](https://www.npmjs.com/package/debug) module?

Thank you.

**Comment by pcxiong** [comment]
Currently, maybe we can use `log: { verbose: false }` in clientOptions when NODE_ENV=production or just `log: { verbose: process.env.NODE_ENV !== 'production' }`, which is not mentioned in the doc.

**Comment by vadimpronin** [comment]
Sorry for long delay, I've been on vacation and could not make an appropriate fix.
In 0.6.0 I've added 5 log levels:
QUIET - basically no logs
ERRORS - only errors
NORMAL - only "server started" and "server stopped" messages
VERBOSE - (default) corresponds to what was previously non-verbose log. I.e. all the connection messages, guacd handshake and probably a few more.
DEBUG - corresponds to what previously was `verbose: true` i.e. prints all the guac protocol exchange between client and guacd
   
Also now you can redefine standard logging functions. By default guacamole-lite using `console.log` and `console.error` functions for logging, but you can write your own functions (for example if you want to redirect log elsewhere) and pass them through log: { stdLog: yourStdLogFunc, errorLog: yourErrorLogFunc}

I've added corresponding sections to README
