### ISSUE TITLE
newConnection usage

### ISSUE THREAD

**Issue by dnapier** [vadimpronin/guacamole-lite#21]
Hi, I'm trying to understand when newConnection gets called, if ever.  Being outside of the constructor, I'm looking for a call or callback for it, but can't find one.  Does it get exported as an event through EventEmitter?

**Comment by vadimpronin** [comment]
Hey,
It's called every time there's a new incoming websocket connection.
WS emits "connection" event and we attach newConnection as callback for this event here https://github.com/vadimpronin/guacamole-lite/blob/master/lib/Server.js#L128

**Comment by dnapier** [comment]
Ah!  Thanks so much for that, I totally missed the binding.
