### ISSUE TITLE
How can I create "MySuperSecretKeyForParamsToken12" ?

### ISSUE THREAD

**Issue by mfarkan** [vadimpronin/guacamole-lite#38]
I could not find this key in the documentation. Where did you guys define this key? In guacd? Should I generate this key in gua server files such as user-mapping.xml or etc? Any ideas?

**Comment by vadimpronin** [comment]
Just generate your own 32-byte long string

**Comment by mfarkan** [comment]
Okay but how the server understand this token and decrypt this object? Am I missing something?

**Comment by vadimpronin** [comment]
You put the same key in both pieces of code: the one that generates the token and the one the verifies.
There are examples in PHP and NodeJS how to generate the token and this key is used to encrypt it.

Basically "your system" (into which you want to integrate Guacamole) generates the token in which it encrypts all the connection parameters. Then it feeds this token to the browser and then the browser connects to guacamole-lite server and gives the token to it. The guacamole-lite server then decrypts the token and establishes the connection.
Obviously both parts ("your system" and guacamole-lite server) must have the same encryption/decryption key

**Comment by mfarkan** [comment]
hmm, I see it's actually not integration key for guacd between client. I can use this token(connectionstring) without encryption and sending to guacd for just dummy purposes.
