### ISSUE TITLE
Node.js token generation example

### ISSUE THREAD

**Issue by fredericosilva** [vadimpronin/guacamole-lite#6]
Hello, congrats about the README it would have saved me some time :)

On my usage I had to generate the token from node.js.

    const crypto = require('crypto');
    const encrypt = data => {
        const iv = crypto.randomBytes(16);
        const cipher = crypto.createCipheriv(clientOptions.cypher, clientOptions.key, iv);

        let crypted = cipher.update(JSON.stringify(data), 'utf8', 'base64');
        crypted += cipher.final('base64');

        const c = {
            iv: iv.toString('base64')
          , value: crypted
        };

        return new Buffer(JSON.stringify(c)).toString('base64');
    };

What do you think about adding it on README?

**Comment by vadimpronin** [comment]
Just did. Thank you!

**Comment by fredericosilva** [comment]
👍
